### PR TITLE
Fix looking left crash

### PR DESCRIPTION
**Pull request by Troyboy3939**
Just returns 0 on GetButtonState if joyBtn is less than 0, since thats used as an index.

### CODE REVIEW

**Comment by GrimMaple** [comment]
The diff is showing the `dllmain.cpp` as a binary file, do you have any idea why that might be happening?

**Comment by Fierelier** [comment]
@GrimMaple This is very likely due to the text file being saved as UTF-16 with BOM or something similar to that. If you take his text file, convert it back to UTF-8 and commit it yourself, you should see the correct diff and previews working and so on.

**Comment by Fruit911** [comment]
please fix the problem with the looking left in events.. lost 4 cars now because of stickdrift.. otherwise the fix is ok.

**Comment by GrimMaple** [comment]
Obsolete now

**Pull request closed without merging**
